language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/
notifications:
  email: false
install: true
script: "if [ ${TRAVIS_PULL_REQUEST} = 'false' ] && [ ${TRAVIS_BRANCH} = 'master' ]; then mvn deploy --settings .travis_settings.xml; else mvn test -B; fi"
