bots:
  - host: localhost
    name: MyInternalBotName
    nick: CraftIRC
    debug-output:
      exceptions: false
      input: false
      output: false
endpoints:
  - name: Chat
    type: mc-chat
  - name: Join
    type: mc-join
  - name: Quit
    type: mc-quit
  - name: IRC
    type: irc
    extra:
      bot: MyInternalBotName
      channel: "#craftirc"
links:
  - source: Chat
    target: IRC
    filters:
      - color
      - type: antihighlight
        splitter: " "
        variable: SENDER_NAME
      - type: datamapper
        message: "<%SENDER_NAME%> %MESSAGE_TEXT%"
      - nobutts
  - source: IRC
    target: Chat
    filters:
      - color
      - type: datamapper
        message: "[IRC] <%SENDER_NAME%> %MESSAGE_TEXT%"
  - source: Join
    target: IRC
  - source: Quit
    target: IRC
repeatable-filters:
  nobutts:
    type: regex
    value: MESSAGE_TEXT
    pattern: butts
    action: drop
  colorize:
    type: color