endpoints:
  - name: Game
    type: minecraft
  - name: IRC
    type: irc
    extra:
      bot: MyInternalBotName
      channel: '#craftirc'
    filters:
      - type: antihighlight
        splitter: " "
        variable: SENDER_NAME
      - type: datamapper
        message: "<%SENDER_NAME%> %MESSAGE_TEXT%"
      - type: regex
        pattern: "butts"
        value: MESSAGE_TEXT
        action: drop
bots:
  - name: MyInternalBotName
    nick: CraftIRC
    host: localhost
links:
  - source: Game
    target: IRC
    bidirectional: true