bots:
  - host: localhost
    name: MyInternalBotName
    nick: CraftIRC
endpoints:
  - name: Game
    type: minecraft
  - name: IRC
    type: irc
    extra:
      bot: MyInternalBotName
      channel: "#craftirc"
links:
  - source: Game
    target: IRC
    filters:
      - color
      - type: antihighlight
        splitter: " "
        variable: SENDER_NAME
      - type: datamapper
        message: "<%SENDER_NAME%> %MESSAGE_TEXT%"
      - nobutts
  - source: IRC
    target: Game
    filters:
      - color
      - type: datamapper
        message: "[IRC] <%SENDER_NAME%> %MESSAGE_TEXT%"
repeatable-filters:
  nobutts:
    type: regex
    value: MESSAGE_TEXT
    pattern: butts
    action: drop
  colorize:
    type: color