bots:
  - host: localhost
    name: MyInternalBotName
    nick: CraftIRC
    debug-output:
      exceptions: false
      input: false
      output: false
endpoints:
  - name: Chat
    type: mc-chat
  - name: Join
    type: mc-join
  - name: Quit
    type: mc-quit
  - name: IRC
    type: irc
    extra:
      bot: MyInternalBotName
      channel: "#craftirc"
links:
  - source: Chat
    target: IRC
    filters:
      - colorize
      - type: antihighlight
        splitter: " "
        variable: SENDER_NAME
      - type: datamapper
        message: "<%SENDER_NAME%> %MESSAGE_TEXT%"
      - nobutts
  - source: IRC
    target: Chat
    filters:
      - colorize
      - type : regex
        value: IRC_PREFIX
        action: replace
        pattern: "@"
        replacement: "[BOSS]"
      - type: datamapper
        message: "[IRC] <%IRC_PREFIX%%SENDER_NAME%> %MESSAGE_TEXT%"
  - source: Join
    target: IRC
  - source: Quit
    target: IRC
repeatable-filters:
  nobutts:
    type: regex
    value: MESSAGE_TEXT
    pattern: butts
    action: drop
  colorize:
    type: color
commands:
  - command: version
    endpoints: [irc, mc-cmd]
  - command: players
    endpoints: irc
    permissions:
      irc: ["@",+]
  - command: exec
    endpoints: irc
    permissions:
      irc: "@"
  - command: ircraw
    rename: raw
    endpoints: [irc, mc-cmd] # mc-cmd unnamed command endpoint eg. /craftirc raw
    permissions:
      mc: craftirc.raw
      irc: "@"
