bots:
  - host: localhost
    name: MyInternalBotName
    nick: CraftIRC
endpoints:
  - name: Game
    type: minecraft
  - name: IRC
    type: irc
    extra:
      bot: MyInternalBotName
      channel: "#craftirc"
links:
  - source: Game
    target: IRC
    filters:
      - splitter: " "
        type: antihighlight
        variable: SENDER_NAME
      - message: "<%SENDER_NAME%> %MESSAGE_TEXT%"
        type: datamapper
      - nobutts
  - source: IRC
    target: Game
    filters:
      - message: "[IRC] <%SENDER_NAME%> %MESSAGE_TEXT%"
        type: datamapper
      - nobutts
repeatable-filters:
  nobutts:
    type: regex
    value: MESSAGE_TEXT
    pattern: butts
    action: drop